// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const mongoose = require('mongoose');

// This section contains the properties of your model, mapped to your collection's properties.
// Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
const schema = mongoose.Schema({
  'food_item_description': String,
  'food_item_id': String,
  'food_item_image': String,
  'food_item_name': String,
  'food_item_price': String,
  'food_item_resturand_id': String,
  'food_item_type_id': String,
}, {
  timestamps: false,
});

module.exports = mongoose.model('foodItems', schema, 'food_items');
