// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const mongoose = require('mongoose');

// This section contains the properties of your model, mapped to your collection's properties.
// Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
const schema = mongoose.Schema({
  'categories': { type: [mongoose.Schema.Types.ObjectId], ref: 'categories' },
  'category': mongoose.Schema.Types.ObjectId,
  'createdAt': Date,
  'description': String,
  'link_to_alibaba': String,
  'link_to_aliexpress': String,
  'link_to_amazon': String,
  'link_to_ebay': String,
  'link_to_etsy': String,
  'link_to_facebook': String,
  'link_to_shopify': String,
  'link_to_walmart': String,
  'name': String,
  'price_range_from': Number,
  'price_range_to': Number,
  'updatedAt': Date,
  'uploaded_by': mongoose.Schema.Types.ObjectId,
}, {
  timestamps: false,
});

module.exports = mongoose.model('products', schema, 'products');
